{% set name = "xpdtools" %}
{% set version = "0.1.2" %}
{% set sha256 = "af9e203808335bd1b24af9be4fe151d64e3aa8d8c6a2ac92e7c9a85ba18c86cb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://github.com/xpdAcq/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - image_to_iq = xpdtools.cli.process_tiff:run_main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - scikit-beam
    - pyyaml
    - pyfai
    - streamz_ext
    - fire
    - pims
    - fabio
    - numba
    - matplotlib


test:
  imports:
    - xpdtools
    - xpdtools.tools
    - xpdtools.cli.process_tiff
  commands:
    - image_to_iq -- --help

about:
  home: https://github.com/xpdAcq/xpdtools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Analysis Tools for XPD'

  doc_url: https://xpdacq.github.io/xpdtools/
  dev_url: https://github.com/xpdAcq/xpdtools

extra:
  recipe-maintainers:
    - CJ-Wright
