travis:
  secure:
    BINSTAR_TOKEN: prNgaN4ojrJGp20k9o9ESkT3pTvYcIZCpXxPjU1nDlkY2kerY7GyD89FbGRQnCJy9zsHULmKd0oYVS4NW9AnqMeAvQ4zMt3yJI2mkO9jm5Eq6TXMT1fPIYp0ou4qWtIkUV3Yozz+0iHnNA2A7yXlifrs9uQwwbI/e0+8d4HU61uUkSSn8f0FEFmjzFu14w2G2GNNxCPvPCezCJeUjlhRrWkAbPneLpPK3toWepMq/cTlojqIcXnKUXtLOXsbcAm86/yUwOtOw3J7TXDnuj21F8dlNQo7dglt2sHZjlcJ8DRWASp1fiLG3kYparrmScsHH5Lpn2rD0D0TQd8lS+YkDNDhaSC0tRBScRLQssp51o3mzf9xuFT1Icm9JPPjpfRC3ySkdUYMeT/W++BDsHQhMWGHg9gMNKdQmlI+ek2dEa218D7QDbBl2nclyBS/PHV4Qie65gwyfwPS9BejNWuxiJpn3mFik1d7YVUDvElBGo9HSe0inb98lkXFueF62z/61640wCgxFLbPbz8dwU+FX+HjAwdLV5+IrG76tQ7cT+kPSiSJQxMaqzCMsfiBOvJJLU4xqAXYYO5K4C0wZiXqM6nqA7ZTjKzpSK4ZsfRu2GECiKECZp8d3ZMnAWx65pTv/x7/BIVPsgE6f2wXa2oSFJlernKg/J3stLwPpFRlM4M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
